app:
  image: nfin
  ports:
    - "84:3000"
    - "85:4000"
    
  links:
    - mongo
  environment:
    - ROOT_URL=http://localhost
    - MONGO_URL=mongodb://mongo:27017/meteor
  restart: always
mongo:
  image: mongo:latest 
  restart: always
